dependencies {
    api("org.yaml:snakeyaml")
    api("org.slf4j:slf4j-api")
    api("org.slf4j:jul-to-slf4j")
    api("ch.qos.logback:logback-classic")
    api("org.springframework:spring-core")
    api("org.springframework:spring-beans")
    api("org.springframework:spring-context")
    api("org.springframework.boot:spring-boot")
    compileOnlyApi("org.jetbrains.kotlin:kotlin-stdlib")
    compileOnlyApi("org.jetbrains.kotlin:kotlin-reflect")
    compileOnlyApi("joda-time:joda-time")
    compileOnlyApi("org.joda:joda-convert")
    compileOnlyApi("jakarta.validation:jakarta.validation-api")
    testImplementation("commons-io:commons-io")
    // testImplementation("org.springframework.boot:spring-boot-starter-web")
}
