rootProject.name = "clever-app"
include("clever-spring")
include("clever-core")
include("clever-web")
include("clever-security")
include("clever-groovy")
include("clever-data-commons")
include("clever-data-dynamic-sql")
include("clever-data-jdbc")
include("clever-data-jdbc-meta")
include("clever-data-redis")
include("clever-data-rabbitmq")
include("clever-task")
include("clever-task-ext")
include("clever-boot")
