dependencies {
    api(project(":clever-spring"))
    api("cglib:cglib")
    api("com.fasterxml.jackson.core:jackson-databind")
    api("org.apache.commons:commons-lang3")
    api("commons-io:commons-io")
    api("commons-codec:commons-codec")
    api("org.json:json")
    api("com.fasterxml.jackson.datatype:jackson-datatype-joda")
    api("com.google.guava:guava")
    api("com.squareup.okhttp3:okhttp")
    // 可选依赖
    compileOnly("com.squareup.retrofit2:converter-jackson")
    compileOnly("org.apache.commons:commons-text")
    compileOnly("com.google.zxing:javase")
    compileOnly("javax.servlet:javax.servlet-api")
    compileOnly("javax.validation:validation-api")
    compileOnly("org.hibernate.validator:hibernate-validator")
    compileOnly("com.github.cage:cage")
    compileOnly("com.github.axet:kaptcha")
    compileOnly("com.github.bingoohuang:patchca")
    compileOnly("com.belerweb:pinyin4j")
    // 单元测试
    testImplementation("org.hibernate.validator:hibernate-validator")
    testImplementation("org.glassfish:javax.el")
}
