logging:
  config: classpath:logback-app.xml
  file:
    name: '${clever.application.name:server}'
    path: './logs/${logging.file.name}'
  level:
    root: info
    org.clever.jdbc.datasource.DataSourceTransactionManager: info
    org.clever.jdbc.datasource.DataSourceUtils: info
    org.clever.core.HotReloadClassLoader: debug
    org.clever.security: debug
    #com.zaxxer.hikari.HikariConfig: debug
    #org.eclipse.jetty.util.log: warn

clever:
  profiles.active: dev
  application.name: clever-boot

rootPath: "./"

jdbc:
  metrics:
    enable: true
    ignoreSql:
      - 'begin dbms_output.enable(); end;'
      - 'declare     num integer := 1000; begin     dbms_output.get_lines(?, num);     dbms_output.disable(); end;'
      - 'select 1'
      - 'select 1 from dual'
    maxSqlCount: 200
    histogram: [ 20, 50, 100, 200, 500, 1000, 2000, 5000, 20000 ]
    histogramTopN: 3
  global:
    driverClassName: 'com.p6spy.engine.spy.P6SpyDriver'
    autocommit: true
    maximumPoolSize: 100
    minimumIdle: 5
    maxLifetime: 21600000
    connectionTimeout: 30000
    connectionTestQuery: 'select 1'
    exceptionOverrideClassName: 'org.clever.data.jdbc.hikari.HikariPreventQueryTimeoutEviction'
    #dataSourceProperties:
    #  stringtype: unspecified

web:
  echo:
    enable: true
    ignorePaths:
      - '/**/*.png'
      - '/**/*.ico'
      - '/**/*.jpg'
      - '/**/*.gif'
      - '/**/*.js'
      - '/**/*.css'
      - '/**/*.html'
      - '/**/*.ts'
      - '/**/*.tsx'
      - '/**/*.map'
      - '/**/*.ttf'
      - '/**/*.woff'
      - '/**/*.woff2'
      - '/**/*.pdf'
  cors:
    enable: true
    pathPattern: [ '/**' ]
    allowedOriginPatterns: [ '*' ]
    allowedOrigins: [ ]
    allowedMethods: [ '*' ]
    allowedHeaders: [ '*' ]
    exposedHeaders: [ ]
    allowCredentials: true
    maxAge: 3600
  resources:
    enable: true
    mappings:
      - hostedPath: '/xml/logback.xml'
        location: './clever-boot/src/main/resources/logback-app.xml'
        cachePeriod: 30d
      - hostedPath: '/static/'
        location: './clever-boot/src/main/resources/static'
        cachePeriod: 30d
      - hostedPath: '/static/'
        location: 'classpath:static/'
        cachePeriod: 30d
