logging:
  config: classpath:logback-app.xml
  file:
    name: '${clever.application.name:server}'
    path: './logs/${logging.file.name}'
  level:
    root: info
    org.clever.jdbc.datasource.DataSourceTransactionManager: info
    org.clever.jdbc.datasource.DataSourceUtils: info
    org.clever.core.HotReloadClassLoader: debug
    org.clever.security: debug
    #com.zaxxer.hikari.HikariConfig: debug
    #org.eclipse.jetty.util.log: warn

clever:
  profiles.active: dev
  application.name: clever-boot

rootPath: "./"

jdbc:
  p6spylog:
    slow: 800
    ignoreSql:
      - 'begin dbms_output.enable(); end;'
      - 'declare     num integer := 1000; begin     dbms_output.get_lines(?, num);     dbms_output.disable(); end;'
      - 'select 1'
      - 'select 1 from dual'
      - 'select now(6) from dual'
    ignoreContainsSql:
      - 'task_http_job'
      - 'task_java_job'
      - 'task_job'
      - 'task_job_log'
      - 'task_job_trigger'
      - 'task_job_trigger_log'
      - 'task_js_job'
      - 'task_report'
      - 'task_scheduler'
      - 'task_scheduler_log'
      - 'task_shell_job'
  metrics:
    enable: true
    maxSqlCount: 200
    histogram: [ 20, 50, 100, 200, 500, 1000, 2000, 5000, 20000 ]
    histogramTopN: 3
  global:
    driverClassName: 'com.p6spy.engine.spy.P6SpyDriver'
    autocommit: true
    maximumPoolSize: 100
    minimumIdle: 5
    maxLifetime: 21600000
    connectionTimeout: 30000
    connectionTestQuery: 'select 1'
    exceptionOverrideClassName: 'org.clever.data.jdbc.hikari.HikariPreventQueryTimeoutEviction'
    #dataSourceProperties:
    #  stringtype: unspecified

redis:
  global:
    mode: Standalone
    ssl: false
    readTimeout: 30s
    connectTimeout: 10s
    shutdownTimeout: 100ms
    clientName: 'clever-app'
    pool:
      enabled: true
      maxIdle: 8
      minIdle: 0
      maxActive: 8
      maxWait: 30s
      timeBetweenEvictionRuns: 1m

web:
  host: '0.0.0.0'
  port: 9090
  server:
    enableDevLogging: false
    ignoreTrailingSlashes: true
    threads:
      min: 8
      max: 250
  jackson:
    locale: 'zh_CN'
    dateFormat: 'yyyy-MM-dd HH:mm:ss'
  http:
    autogenerateEtags: true
    maxRequestSize: 10MB
  echo:
    enable: true
    ignorePaths:
      - '/**/*.png'
      - '/**/*.ico'
      - '/**/*.jpg'
      - '/**/*.gif'
      - '/**/*.js'
      - '/**/*.css'
      - '/**/*.html'
      - '/**/*.ts'
      - '/**/*.tsx'
      - '/**/*.map'
      - '/**/*.ttf'
      - '/**/*.woff'
      - '/**/*.woff2'
      - '/**/*.pdf'
  cors:
    enable: true
    pathPattern: [ '/**' ]
    allowedOriginPatterns: [ '*' ]
    allowedOrigins: [ ]
    allowedMethods: [ '*' ]
    allowedHeaders: [ '*' ]
    exposedHeaders: [ ]
    allowCredentials: true
    maxAge: 3600
  mvc:
    httpMethod: [ 'POST', 'GET' ]
    defTransactional:
      propagation: REQUIRED
      isolation: DEFAULT
      timeout: -1
      readOnly: false
  security:
    ignorePaths:
      - '/favicon.ico'
      - '/dist/**'
      - '/static/**'
      - '/**/*.png'
      - '/**/*.ico'
      - '/**/*.js'
      - '/**/*.css'
      - '/**/*.html'
      - '/**/*.ts'
      - '/**/*.tsx'
      - '/**/*.map'
      - '/**/*.png'
      - '/**/*.jpg'
      - '/**/*.gif'
      - '/**/*.ttf'
      - '/**/*.woff'
      - '/**/*.woff2'
      - '/**/.git'
    ignoreAuthPaths: [ ]
    ignoreAuthFailedPaths: [ ]
    currentUserPath: '/current_user'
    login:
      paths: [ '/login' ]
      postOnly: true
      allowRepeatLogin: true
      concurrentLoginCount: 1
      allowAfterLogin: true
    logout:
      path: '/logout'
    token:
      secretKey: 'security'
      tokenValidity: 30d
      jwtTokenName: 'authorization'
      refreshTokenName: 'refresh-token'
