logging:
  config: classpath:logback-app.xml
  file:
    name: '${clever.application.name:server}'
    path: './logs/${logging.file.name}'
  level:
    root: info
    #org.eclipse.jetty.util.log: warn

web:
  echo:
    ignorePaths:
      - '/**/*.png'
      - '/**/*.ico'
      - '/**/*.jpg'
      - '/**/*.gif'
      - '/**/*.js'
      - '/**/*.css'
      - '/**/*.html'
      - '/**/*.ts'
      - '/**/*.tsx'
      - '/**/*.map'
      - '/**/*.ttf'
      - '/**/*.woff'
      - '/**/*.woff2'
      - '/**/*.pdf'
  cors:
    pathPattern: [ '/**' ]
    allowedOriginPatterns: [ '*' ]
    allowedOrigins: [ ]
    allowedMethods: [ '*' ]
    allowedHeaders: [ '*' ]
    exposedHeaders: [ ]
    allowCredentials: true
    maxAge: 3600

clever:
  profiles.active: dev
  application.name: clever-boot
