app:
  root-path: './'

startup-task:
  pool-size: 8
  timed-task:
    - name: '测试定时任务'
      enable: true
      interval: 120s
      clazz: 'org.clever.app.task.TaskTest'
      method: 'job01'
  cmd-task:
    - name: '持续编译源码'
      enable: false
      async: true
      work-dir: './'
      cmd:
        windows: 'gradlew.bat classes --continuous --watch-fs --build-cache --configuration-cache --configuration-cache-problems=warn'
        linux: './gradlew     classes --continuous --watch-fs --build-cache --configuration-cache --configuration-cache-problems=warn'
        macos: './gradlew     classes --continuous --watch-fs --build-cache --configuration-cache --configuration-cache-problems=warn'

mybatis:
  enable: true
  watcher: true
  interval: 1s
  locations:
    - fileType: filesystem
      location: './clever-boot/src/main/kotlin'
      filter: '**/*.xml'
    - fileType: filesystem
      location: './clever-boot/src/main/java'
      filter: '**/*.xml'
    #- fileType: jar
    #  location: 'classpath*:org/clever/app/**/*.xml'
    #  filter: ''
    #- fileType: filesystem
    #  location: './clever-data-jdbc/src/test/resources/performance_test'
    #  filter: '**/*.xml'

jdbc:
  enable: true
  default-name: 'mysql'
  data-source:
    mysql:
      jdbcUrl: jdbc:p6spy:mysql://192.168.1.211:30019/test
      username: admin
      password: admin123456
      minimumIdle: 2
      maximumPoolSize: 100
      connectionTestQuery: 'select 1 from dual'
    postgresql:
      jdbcUrl: jdbc:p6spy:postgresql://192.168.1.211:30010/test
      username: admin
      password: admin123456
      minimumIdle: 2
      maximumPoolSize: 100
      connectionTestQuery: 'select 1'
      dataSourceProperties:
        stringtype: unspecified
    #oracle:
    #  jdbcUrl: jdbc:p6spy:oracle:thin:@122.9.140.63:1521:wms8dev
    #  username: wms8dev
    #  password: lmis9system
    #  minimumIdle: 2
    #  maximumPoolSize: 100
    #  connectionTestQuery: 'select 1 from dual'

redis:
  enable: true
  default-name: 'default'
  data-source:
    default:
      mode: standalone
      standalone:
        host: '192.168.1.211'
        port: 30007
        database: 0
        password: 'admin123456'

web:
  mvc:
    path: '/api/'
    http-method: [ 'POST', 'GET' ]
    package-mapping:
      - path-Prefix: '/app'
        package-Prefix: 'org.clever.app.mvc'
      - path-Prefix: '/task'
        package-Prefix: 'org.clever.task.manage.mvc'
    allow-packages:
      - 'org.clever.app.mvc.'
      - 'org.clever.task.manage.mvc.'
    transactional-def-datasource: []
    def-transactional:
      datasource: [ ]
      timeout: -1
      read-only: false
    hot-reload:
      enable: true
      # watchFile: './build/.hotReload'
      interval: 1s
      exclude-packages:
        - 'org.clever.task.core.model'
      exclude-classes:
#        - 'org.clever.task.core.model.JobInfo'
#        - 'org.clever.task.core.model.AbstractTrigger'
#        - 'org.clever.task.core.job.JobContext'
      locations:
        - './clever-boot/out/production/classes'
        - './clever-task/out/production/classes'
        #- './clever-boot/build/classes/java/main'
        #- './clever-boot/build/classes/kotlin/main'
        #- './clever-task/build/classes/java/main'
  security:
    enable: false
    dataSource:
      jdbcName: "mysql"
      enableRedis: true
      redisName: "default"
      redisNamespace: "security"
