spring:
  application.name: clever
  profiles.active: dev

logging:
  config: classpath:logback-spring.xml
  file:
    name: '${clever.name:server}'
    path: './logs/${logging.file.name}'
  level:
    root: debug
    org.springframework.boot.env.OriginTrackedYamlLoader: debug
    org.springframework.core.env.StandardEnvironment: debug
    org.springframework.boot.context.logging.LoggingBootstrapTest: info

app:
  root-path: './'

jdbc:
  p6spylog:
    enable: true
    slow: 800
    ignore-sql:
      - 'begin dbms_output.enable(); end;'
      - 'declare     num integer := 1000; begin     dbms_output.get_lines(?, num);     dbms_output.disable(); end;'
      - 'select 1'
      - 'select 1 from dual'
      - 'select now()'
      - 'select now(6) from dual'
    ignore-contains-sql:
      - 'pg_advisory'
      - 'pg_try_advisory'
      - ' task_http_job '
      - ' task_java_job '
      - ' task_job '
      - ' task_job_log '
      - ' task_job_trigger '
      - ' task_job_trigger_log '
      - ' task_js_job '
      - ' task_report '
      - ' task_scheduler '
      - ' task_scheduler_log '
      - ' task_shell_job '
      - ' task_job_console_log '
      - ' task_scheduler_cmd '
  metrics:
    enable: true
    max-sql-count: 200
    histogram: [ 20, 50, 100, 200, 500, 1000, 2000, 5000, 20000 ]
    histogram-top-n: 3
  global:
    driverClassName: 'com.p6spy.engine.spy.P6SpyDriver'
    autocommit: true
    maximumPoolSize: 100
    minimumIdle: 5
    maxLifetime: 21600000
    connectionTimeout: 30000
    connectionTestQuery: 'select 1'
    exceptionOverrideClassName: 'org.clever.data.jdbc.hikari.HikariPreventQueryTimeoutEviction'
    #dataSourceProperties:
    #  stringtype: unspecified
